//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string DepartmentNo { get; set; }
        public string DepartmentName { get; set; }
        public string BrandNo { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string day1 { get; set; }
        public string day2 { get; set; }
        public string day3 { get; set; }
        public string day4 { get; set; }
        public string day5 { get; set; }
        public string day6 { get; set; }
        public string day0 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string PositionX { get; set; }
        public string PositionY { get; set; }
        public string CouponMsg { get; set; }
        public string Introduce { get; set; }
        public string PackageName { get; set; }
        public string Image { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string App { get; set; }
        public string Open_flg { get; set; }
        public string CutHair { get; set; }
        public string DyeHair { get; set; }
        public string PermHair { get; set; }
        public string CareHair { get; set; }
        public string Createdate { get; set; }
    }
}
