//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designer
    {
        public string DesignerNo { get; set; }
        public string DepartmentNo { get; set; }
        public string DesignerName { get; set; }
        public string NickName { get; set; }
        public string Introduce { get; set; }
        public string Image { get; set; }
        public string Createdate { get; set; }
    }
}
