//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dreport
    {
        public string d_no { get; set; }
        public int yl_id { get; set; }
        public string yy { get; set; }
        public string mm { get; set; }
        public string it_no { get; set; }
        public string bt_no { get; set; }
        public string mt_no { get; set; }
        public string st_no { get; set; }
        public Nullable<int> qty { get; set; }
        public string remark { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modi_user { get; set; }
        public Nullable<System.DateTime> modi_date { get; set; }
    }
}
