//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string it_no { get; set; }
        public string it_name { get; set; }
        public string bt_no { get; set; }
        public string mt_no { get; set; }
        public string st_no { get; set; }
        public string mk_no { get; set; }
        public string spec { get; set; }
        public Nullable<decimal> price { get; set; }
        public string unit { get; set; }
        public string remark { get; set; }
        public int status { get; set; }
    }
}
