//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class misEntities2 : DbContext
    {
        public misEntities2()
            : base("name=misEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<sys_pgdetail> sys_pgdetail { get; set; }
        public virtual DbSet<sys_pgmaster> sys_pgmaster { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<BirthMsg> BirthMsg { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dept_Member> Dept_Member { get; set; }
        public virtual DbSet<Designer> Designer { get; set; }
        public virtual DbSet<HairMsg> HairMsg { get; set; }
        public virtual DbSet<Headmsg> Headmsg { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Member_Department> Member_Department { get; set; }
        public virtual DbSet<MemberOrder> MemberOrder { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_brand> product_brand { get; set; }
        public virtual DbSet<product_channel> product_channel { get; set; }
        public virtual DbSet<PushList> PushList { get; set; }
        public virtual DbSet<PushMsg> PushMsg { get; set; }
        public virtual DbSet<PushService> PushService { get; set; }
        public virtual DbSet<ScheduleTable> ScheduleTable { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<sys_pgdetail_group> sys_pgdetail_group { get; set; }
        public virtual DbSet<sys_pgmaster_group> sys_pgmaster_group { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
    }
}
