//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string product_no { get; set; }
        public string ftype { get; set; }
        public string brand_no { get; set; }
        public string product_type_no { get; set; }
        public string name { get; set; }
        public string ptype { get; set; }
        public string detail { get; set; }
        public string fun_detail { get; set; }
        public string star { get; set; }
        public string up_flg { get; set; }
        public string share { get; set; }
        public string sort { get; set; }
        public string pic_s { get; set; }
        public string pic_l_type { get; set; }
        public string pic_l { get; set; }
        public string youtube { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> price_favo { get; set; }
        public string on_shelf { get; set; }
        public string off_shelf { get; set; }
        public string url { get; set; }
        public string remark { get; set; }
        public string cfm_flg { get; set; }
        public Nullable<System.DateTime> cCreDate { get; set; }
        public string cCreUser { get; set; }
        public Nullable<System.DateTime> cModDate { get; set; }
        public string cModUser { get; set; }
        public Nullable<System.DateTime> cCfmDate { get; set; }
        public string cCfmUser { get; set; }
        public string source { get; set; }
    
        public virtual product_type product_type { get; set; }
    }
}
