//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_type()
        {
            this.product = new HashSet<product>();
        }
    
        public string no { get; set; }
        public string name { get; set; }
        public string cfm_flg { get; set; }
        public Nullable<System.DateTime> cCreDate { get; set; }
        public string cCreUser { get; set; }
        public Nullable<System.DateTime> cModDate { get; set; }
        public string cModUser { get; set; }
        public Nullable<System.DateTime> cCfmDate { get; set; }
        public string cCfmUser { get; set; }
        public string source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
    }
}
