//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class purchaseEntities : DbContext
    {
        public purchaseEntities()
            : base("name=purchaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mreport> mreport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<btype> btype { get; set; }
        public virtual DbSet<dreport> dreport { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<make> make { get; set; }
        public virtual DbSet<mm> mm { get; set; }
        public virtual DbSet<mtype> mtype { get; set; }
        public virtual DbSet<stype> stype { get; set; }
    }
}
