//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushMsg
    {
        public string SNO { get; set; }
        public string cContent { get; set; }
        public Nullable<byte> cIsEnable { get; set; }
        public string cPublishType { get; set; }
        public Nullable<System.DateTime> cPublishDate { get; set; }
        public string cPublishTime { get; set; }
        public string cPublishAll { get; set; }
        public string DepartmentNo { get; set; }
        public string MemberNo { get; set; }
        public string HeadmsgNo { get; set; }
    }
}
