//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTable
    {
        public string ScheduleNo { get; set; }
        public string DesignerNo { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string DType { get; set; }
        public string Field0000 { get; set; }
        public string Field0030 { get; set; }
        public string Field0100 { get; set; }
        public string Field0130 { get; set; }
        public string Field0200 { get; set; }
        public string Field0230 { get; set; }
        public string Field0300 { get; set; }
        public string Field0330 { get; set; }
        public string Field0400 { get; set; }
        public string Field0430 { get; set; }
        public string Field0500 { get; set; }
        public string Field0530 { get; set; }
        public string Field0600 { get; set; }
        public string Field0630 { get; set; }
        public string Field0700 { get; set; }
        public string Field0730 { get; set; }
        public string Field0800 { get; set; }
        public string Field0830 { get; set; }
        public string Field0900 { get; set; }
        public string Field0930 { get; set; }
        public string Field1000 { get; set; }
        public string Field1030 { get; set; }
        public string Field1100 { get; set; }
        public string Field1130 { get; set; }
        public string Field1200 { get; set; }
        public string Field1230 { get; set; }
        public string Field1300 { get; set; }
        public string Field1330 { get; set; }
        public string Field1400 { get; set; }
        public string Field1430 { get; set; }
        public string Field1500 { get; set; }
        public string Field1530 { get; set; }
        public string Field1600 { get; set; }
        public string Field1630 { get; set; }
        public string Field1700 { get; set; }
        public string Field1730 { get; set; }
        public string Field1800 { get; set; }
        public string Field1830 { get; set; }
        public string Field1900 { get; set; }
        public string Field1930 { get; set; }
        public string Field2000 { get; set; }
        public string Field2030 { get; set; }
        public string Field2100 { get; set; }
        public string Field2130 { get; set; }
        public string Field2200 { get; set; }
        public string Field2230 { get; set; }
        public string Field2300 { get; set; }
        public string Field2330 { get; set; }
        public string Memo0000 { get; set; }
        public string Memo0030 { get; set; }
        public string Memo0100 { get; set; }
        public string Memo0130 { get; set; }
        public string Memo0200 { get; set; }
        public string Memo0230 { get; set; }
        public string Memo0300 { get; set; }
        public string Memo0330 { get; set; }
        public string Memo0400 { get; set; }
        public string Memo0430 { get; set; }
        public string Memo0500 { get; set; }
        public string Memo0530 { get; set; }
        public string Memo0600 { get; set; }
        public string Memo0630 { get; set; }
        public string Memo0700 { get; set; }
        public string Memo0730 { get; set; }
        public string Memo0800 { get; set; }
        public string Memo0830 { get; set; }
        public string Memo0900 { get; set; }
        public string Memo0930 { get; set; }
        public string Memo1000 { get; set; }
        public string Memo1030 { get; set; }
        public string Memo1100 { get; set; }
        public string Memo1130 { get; set; }
        public string Memo1200 { get; set; }
        public string Memo1230 { get; set; }
        public string Memo1300 { get; set; }
        public string Memo1330 { get; set; }
        public string Memo1400 { get; set; }
        public string Memo1430 { get; set; }
        public string Memo1500 { get; set; }
        public string Memo1530 { get; set; }
        public string Memo1600 { get; set; }
        public string Memo1630 { get; set; }
        public string Memo1700 { get; set; }
        public string Memo1730 { get; set; }
        public string Memo1800 { get; set; }
        public string Memo1830 { get; set; }
        public string Memo1900 { get; set; }
        public string Memo1930 { get; set; }
        public string Memo2000 { get; set; }
        public string Memo2030 { get; set; }
        public string Memo2100 { get; set; }
        public string Memo2130 { get; set; }
        public string Memo2200 { get; set; }
        public string Memo2230 { get; set; }
        public string Memo2300 { get; set; }
        public string Memo2330 { get; set; }
    }
}
